### ISSUE TITLE
"pages/home/miniprogram-render" is not defined

### ISSUE THREAD

**Issue by smartapp-ep** [wechat-miniprogram/kbone-template-vue#1]
build mp exactly as instructed, when running in wechat developer tool, error below occurs. any idea? or did i miss anything? thanks in advance !

`WAService.js:1 Uncaught Error: module "pages/home/miniprogram-render" is not defined
    at require (WAService.js:1)
    at WAService.js:1
    at index.js:1
    at require (WAService.js:1)
    at <anonymous>:11:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1569048469372:1170)
    at HTMLScriptElement.script.onload (appservice?t=1569048469372:1182)`

**Comment by JuneAndGreen** [comment]
You need enter the dist/mp folder and run `npm install`，then using `Npm build` function of devtools(relative doc: https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html).

> PS: all the above has added to README.md now

**Comment by smartapp-ep** [comment]
@JuneAndGreen Thanks!! appreciated. You guys are amazing, didn't expect such fast response on a Saturday!

**Comment by hucheng91** [comment]
@JuneAndGreen  我已经在开发者工具里面build了但还是报这个错

**Comment by hucheng91** [comment]
![image.png-524.5kB](http://static.zybuluo.com/hucheng91/ctdhd83r7xv3whg44bewtyiq/image.png)

**Comment by hucheng91** [comment]
把开发者工具更新到 1.02.1911052 版本，这个问题没有了
