### ISSUE TITLE
这套模板太旧了, 可以更新一下么?

### ISSUE THREAD

**Issue by xujz520** [wechat-miniprogram/kbone-template-vue#12]
如题

**Comment by JuneAndGreen** [comment]
旧是指哪方面？依赖的 vue 版本吗？

**Comment by xujz520** [comment]
vue的版本太旧:
```json
"dependencies": {
    "vue": "^2.5.2",
}
```

我看到 `Kbone/package/vue-improve-loader` 中已经是 `0.3.5` 版本了,  
但是这里的没有使用最新的版本:
```json
"devDependencies": {
    "vue-improve-loader": "^0.1.1"
}
```

**Comment by JuneAndGreen** [comment]
已更新：https://github.com/wechat-miniprogram/kbone-template-vue/commit/3ddf6c92882692c914cbcb8ed5fc0e86752e96fe
