### ISSUE TITLE
这个模板里面我升级了vue成3.0.2，然后就无法引用vue了

### ISSUE THREAD

**Issue by luohan240** [wechat-miniprogram/kbone-template-vue#17]
这个模板里面我升级了vue成3.0.2，然后就无法引用vue了，是其他地方的依赖也要升级吗？引用的方法是改成了vue3的引用方法了

**Comment by JuneAndGreen** [comment]
是需要更新相关依赖，这里有个简单的 vue3 的 demo：https://github.com/Tencent/kbone/tree/develop/examples/demo26 ，可以参考下。
