### ISSUE TITLE
kbone初始化项目tsconfig.json文件报错

### ISSUE THREAD

**Issue by AngelCavalier** [wechat-miniprogram/kbone-template-vue#22]
![image](https://user-images.githubusercontent.com/49480004/128149400-bb4c3217-e10d-4356-b7f1-7bfad3b535b6.png)
如上图所示，这是什么意思

**Comment by JuneAndGreen** [comment]
我这边没有这个报错，也可以正常构建。你可以试试本地这个映射配置能不能用？
