### ISSUE TITLE
有Vite+Kbone+Vue3的template吗？

### ISSUE THREAD

**Issue by cxgreat2014** [wechat-miniprogram/kbone-template-vue#29]
webpack玩不转的表示期待

**Comment by JuneAndGreen** [comment]
webpack 配置比较灵活，社区庞大，且支持大部分 web 框架场景，所以目前来看是会继续使用下去。其他构建工具链基于维护成本就不考虑提供模板了，不过 kbone 本身构建原理并不复杂， 开发者可以自行参考 mp-webpack-plugin 的实现进行构建调整。
