### ISSUE TITLE
组件name属性不应该是App😁

### ISSUE THREAD

**Issue by charmingzuo** [wechat-miniprogram/kbone-template-vue#3]
https://github.com/wechat-miniprogram/kbone-template-vue/blob/2913b8e9c3a2979cee32280f92d3cac7eaf379a3/src/detail/Index.vue#L15

**Comment by JuneAndGreen** [comment]
已 fixed，https://github.com/wechat-miniprogram/kbone-template-vue/commit/22efe3e948d4bd693973eff04cfcee6ecfd2f1cb
