### ISSUE TITLE
请问有没有vue3版本的计划?

### ISSUE THREAD

**Issue by Joyboo** [wechat-miniprogram/kbone-template-vue#30]
`vite` + `vue3` + `typescript` + `pina` 体系

**Comment by JuneAndGreen** [comment]
vue3 有个简易的 demo （ https://github.com/Tencent/kbone/tree/develop/examples/demo26 ），其他非 web 框架相关的工具链开发者可以自己按需调整（或参考 mp-webpack-plugin 插件来适配非 webpack 构建体系的场景）， webpack 本身工具链比较完善，所以 kbone 侧暂不会提供 webpack 之外的构建模板（不过如果是 web 框架，如 vue3 依赖的 dom/bom 接口目前没有支持的情况，可以在 kbone 主仓库提 issue，在目前小程序环境下能兼容的会尽量提供兼容方式）。
