### ISSUE TITLE
module "pages/home/miniprogram-render" is not defined

### ISSUE THREAD

**Issue by ByePastHub** [wechat-miniprogram/kbone-template-vue#6]
尝试了好几遍，也npm i -D miniprogram-render 了，小程序那里把使用npm模块也勾上了，还是报这个错，

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/77905715-5479b500-72b9-11ea-8f74-2ad2f57cdcfe.png)
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html 这个点了么？

**Comment by ByePastHub** [comment]
可能是我Mac系统更新了，npm安装包的时候总会报 `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`，重新安装了一下，现在可以了
