### ISSUE TITLE
eslint 太让人无语了呢

### ISSUE THREAD

**Issue by Hxmic** [wechat-miniprogram/kbone-template-vue#8]
![image](https://user-images.githubusercontent.com/23522154/79939350-74a02c80-8491-11ea-8ffc-be6f3f3b1026.png)

**Comment by JuneAndGreen** [comment]
eslint 规则你可以自己定制的，也可以自行关闭，这个模板只是把这个功能集成进来，同时提供了一份默认规则而已，不是说非要使用和遵守的。
